using System.Text.Json;
using System.Text.Json.Serialization;
using FreezeManager.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;

namespace FreezeManager.Infrastructure.CalendarSync.Seed;

/// <summary>
/// Writes the bundled seed file out of a calendar that has already been synced.
/// </summary>
/// <remarks>
/// The seed used to be hand-maintained, which meant it drifted from reality the moment the season
/// changed -- and a stale seed is not a harmless fallback, it is a calendar with the wrong races in
/// it that the engine will happily treat as authoritative when upstream is down. Generating it from
/// a verified sync makes the fallback a snapshot of something real, and makes refreshing it one
/// command rather than an editing exercise.
/// </remarks>
public static class SeedExporter
{
    private static readonly JsonSerializerOptions ExportOptions = new()
    {
        // Matches the shape of the file it replaces, so regenerating the seed produces a readable
        // diff rather than rewriting every key.
        PropertyNamingPolicy = JsonNamingPolicy.CamelCase,
        WriteIndented = true,
        DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingNull,
        Converters = { new JsonStringEnumConverter() }
    };

    public static async Task<SeedExport> BuildAsync(
        FreezeDbContext db,
        int season,
        CancellationToken cancellationToken = default)
    {
        ArgumentNullException.ThrowIfNull(db);

        var records = await db.RaceEvents
            .AsNoTracking()
            .Include(e => e.Sessions)
            .Include(e => e.ParcFermeWindows)
            .Where(e => e.Season == season)
            .OrderBy(e => e.Round)
            .ToListAsync(cancellationToken);

        var verified = records.Count > 0 && records.All(e => e.IsVerified);

        var document = new SeedCalendarDocument
        {
            Season = season,
            Disclaimer = verified
                ? "Generated by SeedExporter from a verified upstream sync. Every event is marked "
                  + "verified: true because it came from a published source. Regenerate after any "
                  + "calendar change with GET /api/calendar/{season}/seed-export."
                : "Generated by SeedExporter, but at least one event did not come from a published "
                  + "source, so those rows stay verified: false. Run a live sync before exporting if "
                  + "this file is meant to be authoritative.",
            Events = records.Select(ToSeedEvent).ToList()
        };

        return new SeedExport(
            document,
            JsonSerializer.Serialize(document, ExportOptions) + Environment.NewLine,
            records.Count(e => e.Status != Domain.Calendar.EventStatus.Cancelled),
            verified);
    }

    private static SeedEvent ToSeedEvent(RaceEventRecord record) => new()
    {
        Round = record.Round,
        OfficialName = record.OfficialName,
        Circuit = record.Circuit,
        Country = record.Country,
        LocalTimeZoneId = record.LocalTimeZoneId,
        Format = record.Format,
        Status = record.Status,
        Verified = record.IsVerified,
        Sessions = record.Sessions
            .OrderBy(s => s.ScheduledStartUtc)
            .Select(s => new SeedSession
            {
                Type = s.Type,
                Start = UtcTime.ToOffset(s.ScheduledStartUtc),
                End = UtcTime.ToOffset(s.ScheduledEndUtc),
                ActualStart = UtcTime.ToOffset(s.ActualStartUtc),
                ActualEnd = UtcTime.ToOffset(s.ActualEndUtc)
            })
            .ToList(),

        // Parc ferme is exported explicitly rather than left to be re-derived on load, so a window
        // a person entered by hand survives the round trip (decision 13).
        ParcFerme = record.ParcFermeWindows
            .OrderBy(w => w.StartUtc)
            .Select(w => new SeedParcFerme
            {
                Start = UtcTime.ToOffset(w.StartUtc),
                End = UtcTime.ToOffset(w.EndUtc),
                Label = w.Label,
                Derived = w.IsDerived
            })
            .ToList()
    };
}

public sealed record SeedExport(
    SeedCalendarDocument Document,
    string Json,
    int ActiveRoundCount,
    bool AllVerified);
