// <auto-generated />
using System;
using FreezeManager.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FreezeManager.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(FreezeDbContext))]
    [Migration("20260921080323_SyncRunRoundCount")]
    partial class SyncRunRoundCount
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("FreezeManager.Infrastructure.Persistence.AuditEntryRecord", b =>
                {
                    b.Property<long>("Sequence")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Action")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Actor")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Hash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .IsFixedLength();

                    b.Property<DateTime>("OccurredAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("PreviousHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .IsFixedLength();

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Sequence");

                    b.HasIndex("OccurredAtUtc");

                    b.HasIndex("Subject");

                    b.ToTable("AuditEntries", (string)null);
                });

            modelBuilder.Entity("FreezeManager.Infrastructure.Persistence.CalendarSyncRunRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("EventsAdded")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EventsSkipped")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EventsUpdated")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("FromPublishedSource")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Message")
                        .HasColumnType("TEXT");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("Season")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SkippedRoundsJson")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Source")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("StoredRoundCount")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Succeeded")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("CalendarSyncRuns", (string)null);
                });

            modelBuilder.Entity("FreezeManager.Infrastructure.Persistence.ChangeAffectedServiceRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ChangeRequestId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ServiceKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ServiceKey");

                    b.HasIndex("ChangeRequestId", "ServiceKey")
                        .IsUnique();

                    b.ToTable("ChangeAffectedServices", (string)null);
                });

            modelBuilder.Entity("FreezeManager.Infrastructure.Persistence.ChangeApprovalRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Approver")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("ChangeRequestId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Comment")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DecidedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("Decision")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Role")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ChangeRequestId", "Role")
                        .IsUnique();

                    b.ToTable("ChangeApprovals", (string)null);
                });

            modelBuilder.Entity("FreezeManager.Infrastructure.Persistence.ChangeRequestRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BackoutPlan")
                        .HasMaxLength(8000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<int>("Impact")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ImplementationPlan")
                        .HasMaxLength(8000)
                        .HasColumnType("TEXT");

                    b.Property<int>("Likelihood")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Reference")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<int>("ReferenceSequence")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ReferenceYear")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RequestedBy")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("RequestedEndUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("RequestedStartUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("State")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Reference")
                        .IsUnique();

                    b.HasIndex("State");

                    b.HasIndex("ReferenceYear", "ReferenceSequence")
                        .IsUnique();

                    b.ToTable("ChangeRequests", (string)null);
                });

            modelBuilder.Entity("FreezeManager.Infrastructure.Persistence.FreezeOverrideRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ChangeReference")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ExpiresAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<bool>("ExpiryAudited")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GrantDurationMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("GrantedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("IncidentReference")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsBreakGlass")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Justification")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("RequestedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("RequestedBy")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("RetrospectiveCompletedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("RetrospectiveDueAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("RetrospectiveNotes")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<bool>("RetrospectiveOverdueAudited")
                        .HasColumnType("INTEGER");

                    b.Property<int>("State")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UsedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ChangeReference");

                    b.HasIndex("State");

                    b.ToTable("FreezeOverrides", (string)null);
                });

            modelBuilder.Entity("FreezeManager.Infrastructure.Persistence.OverrideApprovalRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Approver")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Comment")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DecidedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("Decision")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FreezeOverrideId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Role")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("FreezeOverrideId", "Role")
                        .IsUnique();

                    b.ToTable("OverrideApprovals", (string)null);
                });

            modelBuilder.Entity("FreezeManager.Infrastructure.Persistence.ParcFermeWindowRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("EndUtc")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDerived")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Label")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("RaceEventId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RaceEventId");

                    b.ToTable("ParcFermeWindows", (string)null);
                });

            modelBuilder.Entity("FreezeManager.Infrastructure.Persistence.RaceEventRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Circuit")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("Format")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LocalTimeZoneId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("OfficialName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<bool>("PinnedByAdmin")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Round")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Season")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Source")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("SyncedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("UpstreamCircuitId")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Season", "Round")
                        .IsUnique();

                    b.ToTable("RaceEvents", (string)null);
                });

            modelBuilder.Entity("FreezeManager.Infrastructure.Persistence.ServiceRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Owner")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("Tier")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("Services", (string)null);
                });

            modelBuilder.Entity("FreezeManager.Infrastructure.Persistence.SessionRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ActualEndUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ActualStartUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("RaceEventId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ScheduledEndUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ScheduledStartUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("RaceEventId", "Type")
                        .IsUnique();

                    b.ToTable("Sessions", (string)null);
                });

            modelBuilder.Entity("FreezeManager.Infrastructure.Persistence.ChangeAffectedServiceRecord", b =>
                {
                    b.HasOne("FreezeManager.Infrastructure.Persistence.ChangeRequestRecord", null)
                        .WithMany("AffectedServices")
                        .HasForeignKey("ChangeRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FreezeManager.Infrastructure.Persistence.ChangeApprovalRecord", b =>
                {
                    b.HasOne("FreezeManager.Infrastructure.Persistence.ChangeRequestRecord", null)
                        .WithMany("Approvals")
                        .HasForeignKey("ChangeRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FreezeManager.Infrastructure.Persistence.OverrideApprovalRecord", b =>
                {
                    b.HasOne("FreezeManager.Infrastructure.Persistence.FreezeOverrideRecord", null)
                        .WithMany("Approvals")
                        .HasForeignKey("FreezeOverrideId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FreezeManager.Infrastructure.Persistence.ParcFermeWindowRecord", b =>
                {
                    b.HasOne("FreezeManager.Infrastructure.Persistence.RaceEventRecord", null)
                        .WithMany("ParcFermeWindows")
                        .HasForeignKey("RaceEventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FreezeManager.Infrastructure.Persistence.SessionRecord", b =>
                {
                    b.HasOne("FreezeManager.Infrastructure.Persistence.RaceEventRecord", null)
                        .WithMany("Sessions")
                        .HasForeignKey("RaceEventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FreezeManager.Infrastructure.Persistence.ChangeRequestRecord", b =>
                {
                    b.Navigation("AffectedServices");

                    b.Navigation("Approvals");
                });

            modelBuilder.Entity("FreezeManager.Infrastructure.Persistence.FreezeOverrideRecord", b =>
                {
                    b.Navigation("Approvals");
                });

            modelBuilder.Entity("FreezeManager.Infrastructure.Persistence.RaceEventRecord", b =>
                {
                    b.Navigation("ParcFermeWindows");

                    b.Navigation("Sessions");
                });
#pragma warning restore 612, 618
        }
    }
}
