// <auto-generated />
using System;
using FreezeManager.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FreezeManager.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(FreezeDbContext))]
    partial class FreezeDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("FreezeManager.Infrastructure.Persistence.CalendarSyncRunRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("EventsAdded")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EventsSkipped")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EventsUpdated")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Message")
                        .HasColumnType("TEXT");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("Season")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Source")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Succeeded")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("CalendarSyncRuns", (string)null);
                });

            modelBuilder.Entity("FreezeManager.Infrastructure.Persistence.ChangeAffectedServiceRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ChangeRequestId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ServiceKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ServiceKey");

                    b.HasIndex("ChangeRequestId", "ServiceKey")
                        .IsUnique();

                    b.ToTable("ChangeAffectedServices", (string)null);
                });

            modelBuilder.Entity("FreezeManager.Infrastructure.Persistence.ChangeRequestRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BackoutPlan")
                        .HasMaxLength(8000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<int>("Impact")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ImplementationPlan")
                        .HasMaxLength(8000)
                        .HasColumnType("TEXT");

                    b.Property<int>("Likelihood")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Reference")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<int>("ReferenceSequence")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ReferenceYear")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RequestedBy")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("RequestedEndUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("RequestedStartUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("State")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Reference")
                        .IsUnique();

                    b.HasIndex("State");

                    b.HasIndex("ReferenceYear", "ReferenceSequence")
                        .IsUnique();

                    b.ToTable("ChangeRequests", (string)null);
                });

            modelBuilder.Entity("FreezeManager.Infrastructure.Persistence.ParcFermeWindowRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("EndUtc")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDerived")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Label")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("RaceEventId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RaceEventId");

                    b.ToTable("ParcFermeWindows", (string)null);
                });

            modelBuilder.Entity("FreezeManager.Infrastructure.Persistence.RaceEventRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Circuit")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("Format")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LocalTimeZoneId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("OfficialName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<bool>("PinnedByAdmin")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Round")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Season")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Source")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("SyncedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("UpstreamCircuitId")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Season", "Round")
                        .IsUnique();

                    b.ToTable("RaceEvents", (string)null);
                });

            modelBuilder.Entity("FreezeManager.Infrastructure.Persistence.ServiceRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Owner")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("Tier")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("Services", (string)null);
                });

            modelBuilder.Entity("FreezeManager.Infrastructure.Persistence.SessionRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ActualEndUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ActualStartUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("RaceEventId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ScheduledEndUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ScheduledStartUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("RaceEventId", "Type")
                        .IsUnique();

                    b.ToTable("Sessions", (string)null);
                });

            modelBuilder.Entity("FreezeManager.Infrastructure.Persistence.ChangeAffectedServiceRecord", b =>
                {
                    b.HasOne("FreezeManager.Infrastructure.Persistence.ChangeRequestRecord", null)
                        .WithMany("AffectedServices")
                        .HasForeignKey("ChangeRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FreezeManager.Infrastructure.Persistence.ParcFermeWindowRecord", b =>
                {
                    b.HasOne("FreezeManager.Infrastructure.Persistence.RaceEventRecord", null)
                        .WithMany("ParcFermeWindows")
                        .HasForeignKey("RaceEventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FreezeManager.Infrastructure.Persistence.SessionRecord", b =>
                {
                    b.HasOne("FreezeManager.Infrastructure.Persistence.RaceEventRecord", null)
                        .WithMany("Sessions")
                        .HasForeignKey("RaceEventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FreezeManager.Infrastructure.Persistence.ChangeRequestRecord", b =>
                {
                    b.Navigation("AffectedServices");
                });

            modelBuilder.Entity("FreezeManager.Infrastructure.Persistence.RaceEventRecord", b =>
                {
                    b.Navigation("ParcFermeWindows");

                    b.Navigation("Sessions");
                });
#pragma warning restore 612, 618
        }
    }
}
